/**
 * API de Seguimiento Global de Activos Logisticos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensorStatus } from './sensorStatus';


export interface AssetStatus { 
    assetId: string;
    status: string;
    healthScore: number;
    lastTelemetry: string;
    sensors: Array<SensorStatus>;
}

