/**
 * API de Seguimiento Global de Activos Logisticos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Asset { 
    id: string;
    name: string;
    type: string;
    location?: string;
    latitude?: number;
    longitude?: number;
}

