/**
 * API de Seguimiento Global de Activos Logisticos
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTelemetryLog { 
    assetId: string;
    timestamp: string;
    temperature: number;
    batteryLevel: number;
    vibration: number;
}

